name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: 'django-test-key'
        DEBUG: 'True'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
        DATABASE_NAME: 'test_db'
        DATABASE_USER: 'postgres'
        DATABASE_PASSWORD: 'postgres'
        DATABASE_HOST: 'localhost'
        DATABASE_PORT: '5432'
      run: |
        python manage.py test
